-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 13:46:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


--          PROJETO 4 TMAB
-- Andre Osorio Magaldi Netto                118041914
-- Joao Paulo Alves Loureiro Da Silva        117196504
-- Rodrigo Bagdadi Benoliel                  118031529


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Milton3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Milton3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Milton3` DEFAULT CHARACTER SET utf8 ;
USE `Milton3` ;

-- -----------------------------------------------------
-- Table `Milton3`.`Carro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`Carro` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`Carro` (
  `Renavam` INT UNSIGNED NOT NULL,
  `Placa` CHAR(7) NOT NULL,
  `Modelo` VARCHAR(20) NOT NULL,
  `Marca` VARCHAR(15) NOT NULL,
  `Cor` VARCHAR(10) NOT NULL,
  `Fotos` LONGBLOB NULL,
  `Ano de Fab` INT UNSIGNED NULL,
  `Kilometragem` INT UNSIGNED NOT NULL,
  `Num. Assentos` INT UNSIGNED NOT NULL,
  `Alugado` BIT NOT NULL,
  PRIMARY KEY (`Renavam`),
  UNIQUE INDEX `Placa_UNIQUE` (`Placa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Milton3`.`Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`Vendedor` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`Vendedor` (
  `id Vendedor` INT UNSIGNED NOT NULL,
  `CPF` INT UNSIGNED NOT NULL,
  `Salário` FLOAT UNSIGNED NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id Vendedor`),
  UNIQUE INDEX `id Vendedor_UNIQUE` (`id Vendedor` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Milton3`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`Clientes` (
  `Email` VARCHAR(45) NOT NULL,
  `CPF` INT UNSIGNED NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  `CNPJ` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `id Cliente` INT UNSIGNED NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `CNH` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  PRIMARY KEY (`id Cliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `Telefone_UNIQUE` (`Telefone` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `id Cliente_UNIQUE` (`id Cliente` ASC) VISIBLE,
  UNIQUE INDEX `Endereço_UNIQUE` (`Endereço` ASC) VISIBLE,
  UNIQUE INDEX `CNH_UNIQUE` (`CNH` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Milton3`.`Contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`Contrato` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`Contrato` (
  `id Contrato` INT UNSIGNED NOT NULL,
  `Validade` DATE NOT NULL,
  `Inicio` DATE NOT NULL,
  PRIMARY KEY (`id Contrato`),
  UNIQUE INDEX `id Contrato_UNIQUE` (`id Contrato` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Milton3`.`Locadora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`Locadora` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`Locadora` (
  `CNPJ` VARCHAR(25) NOT NULL,
  `id. Gerente` INT UNSIGNED NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CNPJ`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `id. Gerente_UNIQUE` (`id. Gerente` ASC) VISIBLE,
  UNIQUE INDEX `Endereço_UNIQUE` (`Endereço` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Milton3`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`Pagamento` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`Pagamento` (
  `id Pagamento` INT UNSIGNED NOT NULL,
  `Valor` FLOAT UNSIGNED NOT NULL,
  `Pagamentocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id Pagamento`),
  UNIQUE INDEX `id Pagamento_UNIQUE` (`id Pagamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Milton3`.`Fecha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`Fecha` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`Fecha` (
  `Vendedor_id Vendedor` INT UNSIGNED NOT NULL,
  `Contrato_id Contrato` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Vendedor_id Vendedor`, `Contrato_id Contrato`),
  INDEX `fk_Fecha_Contrato1_idx` (`Contrato_id Contrato` ASC) VISIBLE,
  CONSTRAINT `fk_Fecha_Vendedor1`
    FOREIGN KEY (`Vendedor_id Vendedor`)
    REFERENCES `Milton3`.`Vendedor` (`id Vendedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Fecha_Contrato1`
    FOREIGN KEY (`Contrato_id Contrato`)
    REFERENCES `Milton3`.`Contrato` (`id Contrato`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Milton3`.`Estabelce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`Estabelce` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`Estabelce` (
  `Contrato_id Contrato` INT UNSIGNED NOT NULL,
  `Pagamento_id Pagamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Contrato_id Contrato`, `Pagamento_id Pagamento`),
  INDEX `fk_Estabelce_Pagamento1_idx` (`Pagamento_id Pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Estabelce_Contrato1`
    FOREIGN KEY (`Contrato_id Contrato`)
    REFERENCES `Milton3`.`Contrato` (`id Contrato`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Estabelce_Pagamento1`
    FOREIGN KEY (`Pagamento_id Pagamento`)
    REFERENCES `Milton3`.`Pagamento` (`id Pagamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Milton3`.`Contrata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`Contrata` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`Contrata` (
  `Locadora_CNPJ` VARCHAR(25) NOT NULL,
  `Vendedor_id Vendedor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Locadora_CNPJ`, `Vendedor_id Vendedor`),
  INDEX `fk_Contrata_Vendedor1_idx` (`Vendedor_id Vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_Contrata_Locadora1`
    FOREIGN KEY (`Locadora_CNPJ`)
    REFERENCES `Milton3`.`Locadora` (`CNPJ`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Contrata_Vendedor1`
    FOREIGN KEY (`Vendedor_id Vendedor`)
    REFERENCES `Milton3`.`Vendedor` (`id Vendedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Milton3`.`Aluga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`Aluga` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`Aluga` (
  `Clientes_id Cliente` INT UNSIGNED NOT NULL,
  `Carro_Renavam` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Clientes_id Cliente`, `Carro_Renavam`),
  INDEX `fk_Aluga_Carro1_idx` (`Carro_Renavam` ASC) VISIBLE,
  CONSTRAINT `fk_Aluga_Clientes1`
    FOREIGN KEY (`Clientes_id Cliente`)
    REFERENCES `Milton3`.`Clientes` (`id Cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Aluga_Carro1`
    FOREIGN KEY (`Carro_Renavam`)
    REFERENCES `Milton3`.`Carro` (`Renavam`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Milton3`.`Paga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`Paga` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`Paga` (
  `Clientes_id Cliente` INT UNSIGNED NOT NULL,
  `Pagamento_id Pagamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Clientes_id Cliente`, `Pagamento_id Pagamento`),
  INDEX `fk_Paga_Pagamento1_idx` (`Pagamento_id Pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Paga_Clientes1`
    FOREIGN KEY (`Clientes_id Cliente`)
    REFERENCES `Milton3`.`Clientes` (`id Cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Paga_Pagamento1`
    FOREIGN KEY (`Pagamento_id Pagamento`)
    REFERENCES `Milton3`.`Pagamento` (`id Pagamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Milton3`.`É contraparte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`É contraparte` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`É contraparte` (
  `Clientes_id Cliente` INT UNSIGNED NOT NULL,
  `Contrato_id Contrato` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Clientes_id Cliente`, `Contrato_id Contrato`),
  INDEX `fk_É contraparte_Contrato1_idx` (`Contrato_id Contrato` ASC) VISIBLE,
  CONSTRAINT `fk_É contraparte_Clientes1`
    FOREIGN KEY (`Clientes_id Cliente`)
    REFERENCES `Milton3`.`Clientes` (`id Cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_É contraparte_Contrato1`
    FOREIGN KEY (`Contrato_id Contrato`)
    REFERENCES `Milton3`.`Contrato` (`id Contrato`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Milton3`.`Faz parte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`Faz parte` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`Faz parte` (
  `Carro_Renavam` INT UNSIGNED NOT NULL,
  `Contrato_id Contrato` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Carro_Renavam`, `Contrato_id Contrato`),
  INDEX `fk_Faz parte_Contrato1_idx` (`Contrato_id Contrato` ASC) VISIBLE,
  CONSTRAINT `fk_Faz parte_Carro1`
    FOREIGN KEY (`Carro_Renavam`)
    REFERENCES `Milton3`.`Carro` (`Renavam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Faz parte_Contrato1`
    FOREIGN KEY (`Contrato_id Contrato`)
    REFERENCES `Milton3`.`Contrato` (`id Contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Milton3`.`Oferece`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`Oferece` ;

CREATE TABLE IF NOT EXISTS `Milton3`.`Oferece` (
  `Locadora_CNPJ` VARCHAR(25) NOT NULL,
  `Carro_Renavam` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Locadora_CNPJ`, `Carro_Renavam`),
  INDEX `fk_Oferece_Carro1_idx` (`Carro_Renavam` ASC) VISIBLE,
  CONSTRAINT `fk_Oferece_Locadora1`
    FOREIGN KEY (`Locadora_CNPJ`)
    REFERENCES `Milton3`.`Locadora` (`CNPJ`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Oferece_Carro1`
    FOREIGN KEY (`Carro_Renavam`)
    REFERENCES `Milton3`.`Carro` (`Renavam`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `Milton3` ;

-- -----------------------------------------------------
-- Placeholder table for view `Milton3`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Milton3`.`view1` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

USE `Milton3`;
DROP  IF EXISTS `Milton3`.`routine1`;

DELIMITER $$
USE `Milton3`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `Milton3`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Milton3`.`view1`;
DROP VIEW IF EXISTS `Milton3`.`view1` ;
USE `Milton3`;

SET SQL_MODE = '';
DROP USER IF EXISTS Teste;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'Teste' IDENTIFIED BY '12345678';

GRANT ALL ON `Milton3`.* TO 'Teste';
GRANT SELECT, INSERT, TRIGGER ON TABLE `Milton3`.* TO 'Teste';
GRANT SELECT ON TABLE `Milton3`.* TO 'Teste';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `Milton3`.* TO 'Teste';
GRANT EXECUTE ON ROUTINE `Milton3`.* TO 'Teste';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
